# Generated by Django 3.1.5 on 2021-01-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelthDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('availability', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_contact', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment_date', models.TimeField()),
                ('patient_history', models.TextField()),
                ('helth_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.helthdepartment')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
