# Generated by Django 3.1.5 on 2021-01-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_history',
            new_name='history',
        ),
    ]
