# Generated by Django 3.1.5 on 2021-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_auto_20210106_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='helth_department',
            field=models.PositiveSmallIntegerField(choices=[(0, 'daily task'), (1, 'work jobs'), (2, 'house needs')], default=0),
        ),
    ]
