# Generated by Django 3.1.5 on 2021-01-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_auto_20210106_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='helth_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.helthdepartment'),
        ),
    ]
