# Generated by Django 3.1.5 on 2021-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_auto_20210107_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
