# Generated by Django 3.1.5 on 2021-01-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_auto_20210109_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
