# Generated by Django 2.2.17 on 2021-02-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_auto_20210213_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='appointment_time',
        ),
    ]
