# Generated by Django 3.1.5 on 2021-01-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='family_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
