# Generated by Django 3.1.5 on 2021-01-21 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210119_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='family_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ارتباط با ما'), (2, 'دوره های آنلاین'), (3, 'سفارش پروژه')], default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
